import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  const [playlists, setPlaylists] = useState([]);

  // Fetch playlists from backend API
  useEffect(() => {
    const fetchPlaylists = async () => {
      try {
        const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/playlists`);
        const data = await response.json();
        setPlaylists(data);
      } catch (error) {
        console.error("Error fetching playlists:", error);
      }
    };

    fetchPlaylists();
  }, []);

  return (
    <>
      <Head>
        <title>Media Playlist App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <h1>Media Playlists</h1>

          {/* Render playlists */}
          {playlists.length > 0 ? (
            <ul>
              {playlists.map((playlist) => (
                <li key={playlist._id}>{playlist.name}</li>
              ))}
            </ul>
          ) : (
            <p>No playlists available</p>
          )}
        </main>
        <footer className={styles.footer}>
          <a href="https://nextjs.org/learn" target="_blank" rel="noopener noreferrer">
            Learn Next.js →
          </a>
        </footer>
      </div>
    </>
  );
}
